/**
 * useFrequencyPlayer — DDS-backed healing frequency synthesis
 *
 * Drop-in replacement for the original OscillatorNode implementation.
 * All audio is now generated by the DDS AudioWorklet (dds-processor.js),
 * providing double-precision phase-continuous synthesis across the entire app.
 *
 * SRS compliance:
 *   FR-002  Phase-continuous — no clicks/pops on parameter changes
 *   FR-003  Sine waveform (default)
 *   FR-004  Smooth amplitude ramping on start/stop
 *   NFR-FREQ-004  Double-precision phase accumulation
 */
import { useState, useRef, useCallback, useEffect } from "react";

export interface Frequency {
  id: string;
  name: string;
  hz: number;
  binauralOffset?: number; // Hz offset for right channel (binaural beats)
  /** When true, DDS engine uses isochronic pulse mode instead of binaural */
  isIsochronic?: boolean;
  category: "solfeggio" | "binaural" | "chakra" | "nature";
  description: string;
  benefit: string;
  color: string;
  isPremium: boolean;
  /** Sanskrit chakra name + pronunciation guide */
  pronunciation?: string;
  /** Chakra position 1-7 (Root=1, Crown=7) for Chakra Map ordering */
  chakraPosition?: number;
}

export const FREQUENCIES: Frequency[] = [
  {
    id: "174hz",
    name: "Foundation",
    hz: 174,
    category: "solfeggio",
    description: "174Hz — The Foundation Tone",
    benefit: "Promotes deep calm, security, and grounding",
    color: "#EF4444",
    isPremium: false,
  },
  {
    id: "285hz",
    name: "Quantum Cognition",
    hz: 285,
    category: "solfeggio",
    description: "285Hz — Quantum Cognition",
    benefit: "Associated with renewal and restoration",
    color: "#F97316",
    isPremium: true,
  },
  {
    id: "396hz",
    name: "Liberation",
    hz: 396,
    category: "solfeggio",
    description: "396Hz — Root Chakra (Mūlādhāra) · Liberation from Fear",
    benefit: "Grounds your energy and releases guilt, fear, and deeply held negative emotions. Traditionally associated with the Root Chakra, this tone is used to build a sense of safety, stability, and belonging.",
    color: "#EAB308",
    isPremium: false,
    pronunciation: "Mūlādhāra · moo-LAH-dah-rah",
    chakraPosition: 1,
  },
  {
    id: "417hz",
    name: "Transmutation",
    hz: 417,
    category: "solfeggio",
    description: "417Hz — Sacral Chakra (Svādhiṣṭhāna) · Transmutation",
    benefit: "Clears traumatic experiences and facilitates positive change. Linked to the Sacral Chakra, it supports creativity, emotional flow, and the release of past patterns that no longer serve you.",
    color: "#84CC16",
    isPremium: true,
    pronunciation: "Svādhiṣṭhāna · svah-DISH-tah-nah",
    chakraPosition: 2,
  },
  {
    id: "432hz",
    name: "Natural Harmony",
    hz: 432,
    category: "solfeggio",
    description: "432Hz — Natural Harmony",
    benefit: "Aligns with nature's frequency, promotes calm",
    color: "#00D4AA",
    isPremium: false,
  },
  {
    id: "528hz",
    name: "Miracle Tone",
    hz: 528,
    category: "solfeggio",
    description: "528Hz — Solar Plexus Chakra (Maṇipūra) · The Miracle Tone",
    benefit: "Known as the 'Love Frequency' and the Miracle Tone. Linked to the Solar Plexus Chakra, it strengthens personal power, confidence, and your sense of purpose.",
    color: "#06B6D4",
    isPremium: false,
    pronunciation: "Maṇipūra · mah-nee-POO-rah",
    chakraPosition: 3,
  },
  {
    id: "639hz",
    name: "Connection",
    hz: 639,
    category: "solfeggio",
    description: "639Hz — Heart Chakra (Anāhata) · Connection & Relationships",
    benefit: "Opens the Heart Chakra to harmonize relationships and deepen compassion. This frequency is used to enhance communication, tolerance, and unconditional love — both for others and for yourself.",
    color: "#3B82F6",
    isPremium: true,
    pronunciation: "Anāhata · ah-NAH-ha-ta",
    chakraPosition: 4,
  },
  {
    id: "741hz",
    name: "Awakening",
    hz: 741,
    category: "solfeggio",
    description: "741Hz — Throat Chakra (Viśuddha) · Awakening Intuition",
    benefit: "Activates the Throat Chakra to support authentic self-expression and clear communication. Traditionally associated with purification and expanded consciousness through honest, purposeful speech.",
    color: "#8B5CF6",
    isPremium: true,
    pronunciation: "Viśuddha · vee-SHOO-dah",
    chakraPosition: 5,
  },
  {
    id: "852hz",
    name: "Spiritual Order",
    hz: 852,
    category: "solfeggio",
    description: "852Hz — Third Eye Chakra (Ājñā) · Spiritual Order",
    benefit: "Awakens the Third Eye Chakra, deepening intuition and inner vision. This frequency is used to return to spiritual order, dissolve illusions, and strengthen the connection between your conscious mind and higher awareness.",
    color: "#A855F7",
    isPremium: true,
    pronunciation: "Ājñā · AHJ-nyah",
    chakraPosition: 6,
  },
  {
    id: "963hz",
    name: "Divine Consciousness",
    hz: 963,
    category: "solfeggio",
    description: "963Hz — Crown Chakra (Sahasrāra) · Divine Consciousness",
    benefit: "Traditionally associated with the Crown Chakra, opening a channel to higher consciousness and universal oneness. Used in meditation to dissolve the boundary between self and the divine, inviting deep spiritual awakening.",
    color: "#EC4899",
    isPremium: true,
    pronunciation: "Sahasrāra · sah-has-RAH-rah",
    chakraPosition: 7,
  },
  {
    id: "binaural-alpha",
    name: "Alpha Waves",
    hz: 200,
    binauralOffset: 10,
    category: "binaural",
    description: "Alpha Binaural — 10Hz beat",
    benefit: "Relaxed alertness, creativity, stress reduction",
    color: "#00D4AA",
    isPremium: false,
  },
  {
    id: "binaural-theta",
    name: "Theta Waves",
    hz: 200,
    binauralOffset: 6,
    category: "binaural",
    description: "Theta Binaural — 6Hz beat",
    benefit: "Deep meditation, REM sleep, restoration",
    color: "#8B5CF6",
    isPremium: true,
  },
  {
    id: "binaural-delta",
    name: "Delta Waves",
    hz: 200,
    binauralOffset: 3,
    category: "binaural",
    description: "Delta Binaural — 3Hz beat",
    benefit: "Deep sleep, nightly reset, unconscious mind",
    color: "#6366F1",
    isPremium: true,
  },
  {
    id: "alpha-isochronic",
    name: "Alpha Isochronic",
    hz: 10,
    isIsochronic: true,
    category: "binaural",
    description: "Alpha Isochronic — 10Hz pulse (no headphones needed)",
    benefit: "Focused clarity and relaxed alertness — works without headphones",
    color: "#F59E0B",
    isPremium: true,
  },
  {
    id: "schumann",
    name: "Schumann Resonance",
    hz: 200,
    binauralOffset: 7.83,
    category: "binaural",
    description: "Schumann Resonance — 7.83Hz (Earth's heartbeat)",
    benefit: "Grounding, balance, and connection to Earth's natural electromagnetic field",
    color: "#22C55E",
    isPremium: true,
  },
];

// ── DDS engine constants ──────────────────────────────────────────────────────
const WORKLET_URL = "/dds-processor.js";
const FADE_TC = 0.3; // seconds time-constant for smooth amplitude transitions

/**
 * Shared AudioContext + worklet singleton.
 * We reuse one AudioContext across all hook instances to avoid hitting the
 * browser's 6-context limit and to ensure the worklet module is only loaded once.
 */
let sharedCtx: AudioContext | null = null;
let workletReady: Promise<void> | null = null;

async function getSharedContext(): Promise<AudioContext> {
  if (!sharedCtx || sharedCtx.state === "closed") {
    sharedCtx = new (
      window.AudioContext ||
      (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext
    )();
    workletReady = sharedCtx.audioWorklet.addModule(WORKLET_URL);
  }
  if (sharedCtx.state === "suspended") await sharedCtx.resume();
  await workletReady;
  return sharedCtx;
}

/**
 * useFrequencyPlayer
 *
 * Same public API as the original OscillatorNode version.
 * Internally uses the DDS AudioWorklet for double-precision synthesis.
 */
export function useFrequencyPlayer() {
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentFrequency, setCurrentFrequency] = useState<Frequency | null>(null);
  const [volume, setVolumeState] = useState(0.6);
  const [playTime, setPlayTime] = useState(0);

  const workletNodeRef = useRef<AudioWorkletNode | null>(null);
  const gainNodeRef = useRef<GainNode | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Tear down the current worklet node (no state changes) ─────────────────
  const teardown = useCallback(() => {
    if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null; }
    const node = workletNodeRef.current;
    const gain = gainNodeRef.current;
    if (node) { node.disconnect(); workletNodeRef.current = null; }
    if (gain) { gain.disconnect(); gainNodeRef.current = null; }
  }, []);

  // ── Stop (with optional fade-out) ─────────────────────────────────────────
  const stopAudio = useCallback((immediate = false) => {
    if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null; }

    const ctx = sharedCtx;
    const gain = gainNodeRef.current;
    const node = workletNodeRef.current;

    if (!ctx || !gain || !node) {
      setIsPlaying(false);
      return;
    }

    if (immediate) {
      teardown();
      setIsPlaying(false);
    } else {
      gain.gain.cancelScheduledValues(ctx.currentTime);
      gain.gain.setValueAtTime(gain.gain.value, ctx.currentTime);
      gain.gain.setTargetAtTime(0, ctx.currentTime, FADE_TC);
      setTimeout(() => {
        teardown();
        setIsPlaying(false);
      }, 1500);
    }
  }, [teardown]);

  // ── Play a Frequency object via DDS ───────────────────────────────────────
  const playFrequency = useCallback(async (freq: Frequency) => {
    // Tear down any existing node immediately (no fade — we're switching)
    teardown();

    let ctx: AudioContext;
    try {
      ctx = await getSharedContext();
    } catch (err) {
      console.error("[DDS] Failed to initialise AudioContext:", err);
      return;
    }

    // Build gain node
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, ctx.currentTime);
    gainNodeRef.current = gain;

    // Build DDS worklet node
    const worklet = new AudioWorkletNode(ctx, "dds-processor", {
      numberOfInputs: 0,
      numberOfOutputs: 1,
      outputChannelCount: [2],
    });
    workletNodeRef.current = worklet;

    // Configure synthesis — wait for the worklet to signal it is ready
    // before sending parameters to avoid dropped messages on slow threads.
    const freqL = freq.hz;
    const freqR = freq.binauralOffset !== undefined
      ? freq.hz + freq.binauralOffset
      : freq.hz;
    const mode = freq.binauralOffset !== undefined ? "binaural" : "mono";

    await new Promise<void>((resolve) => {
      const onReady = (e: MessageEvent) => {
        if (e.data?.type === 'ready') {
          worklet.port.removeEventListener('message', onReady);
          resolve();
        }
      };
      worklet.port.addEventListener('message', onReady);
      worklet.port.start();
      // Fallback: if ready message was already sent before we attached the listener,
      // resolve after a short microtask delay
      setTimeout(resolve, 50);
    });

    worklet.port.postMessage({ type: "setFreq", freqL, freqR });
    worklet.port.postMessage({ type: "setWaveform", waveform: "sine" });
    worklet.port.postMessage({ type: "setMode", mode });
    worklet.port.postMessage({ type: "setIsochronic", enabled: freq.isIsochronic === true });

    // Connect to audio graph
    worklet.connect(gain);
    gain.connect(ctx.destination);

    // Smooth fade-in (FR-004)
    gain.gain.setTargetAtTime(volume, ctx.currentTime, FADE_TC * 0.5);

    setCurrentFrequency(freq);
    setIsPlaying(true);
    setPlayTime(0);

    timerRef.current = setInterval(() => setPlayTime(t => t + 1), 1000);
  }, [teardown, volume]);

  // ── Toggle play/stop for a given frequency ────────────────────────────────
  const togglePlay = useCallback((freq: Frequency) => {
    if (isPlaying && currentFrequency?.id === freq.id) {
      stopAudio();
    } else {
      playFrequency(freq);
    }
  }, [isPlaying, currentFrequency, playFrequency, stopAudio]);

  // ── Volume ────────────────────────────────────────────────────────────────
  const setVolume = useCallback((v: number) => {
    setVolumeState(v);
    if (gainNodeRef.current && sharedCtx) {
      gainNodeRef.current.gain.setTargetAtTime(v, sharedCtx.currentTime, 0.05);
    }
  }, []);

  // ── Cleanup on unmount ────────────────────────────────────────────────────
  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
      workletNodeRef.current?.disconnect();
      gainNodeRef.current?.disconnect();
      // Do NOT close sharedCtx — it is shared across all hook instances
    };
  }, []);

  return {
    isPlaying,
    currentFrequency,
    volume,
    playTime,
    playFrequency,
    stopAudio,
    togglePlay,
    setVolume,
  };
}
